<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LU9FG0N5" failures="5" tests="5" name="Add Customer  Login Test" time="13.448" errors="0" timestamp="2021-05-04T23:45:55 EDT">
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="2.852">
    <failure type="java.lang.AssertionError" message="Customer not added Successfull">
      <![CDATA[java.lang.AssertionError: Customer not added Successfull
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="2.378">
    <failure type="java.lang.AssertionError" message="Customer not added Successfull">
      <![CDATA[java.lang.AssertionError: Customer not added Successfull
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="2.285">
    <failure type="java.lang.AssertionError" message="Customer not added Successfull">
      <![CDATA[java.lang.AssertionError: Customer not added Successfull
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="2.267">
    <failure type="java.lang.AssertionError" message="Customer not added Successfull">
      <![CDATA[java.lang.AssertionError: Customer not added Successfull
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="2.282">
    <failure type="java.lang.AssertionError" message="Customer not added Successfull">
      <![CDATA[java.lang.AssertionError: Customer not added Successfull
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
</testsuite> <!-- Add Customer  Login Test -->
